require("config.set")
require("config.remap")
require("config.lazy")
require("config.dadbod")
require("features.lualine")
require("features.ide.lsp")
require("features.ide.dap")
require("features.ide.formatting")
require("features.ide.treesitter")
require("features.telescope")
require("features.harpoon")
require("features.ia.gen-nvim")
require("features.ide.test")
print("hello from MQ")
