require("config.set")
require("config.remap")
require("config.lazy")
require("config.dadbod")
require("features.lualine")
require("features.ide.lsp")
require("features.ide.dap")
require("features.ide.treesitter")
require("features.telescope")
print("hello from MQ")
